name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.0.5
api-version: 1.16
depend: [Minions-Revamped]

# Update 0.0.5 for Minions-Miner

# * Added loadMinersForOnline method. Loads miners for online players.
# * Moved set placeholders on CreateMinionEntity to below the intial getplaceholders call. Allows the getPlaceholders method to set defaults.