name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.0.6
api-version: 1.16
depend: [Minions-Revamped]

# Update 0.0.6 for Minions-Miner

# Updated Minions-Revamped dependency.
# Updated code to function on lower versions.
# Update "Minable" path to "Mineable" in settings.yml