name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.0.8
api-version: 1.13
depend: [Minions-Revamped]

# Update 0.0.8 for Minions-Miner 

# Updated Minions-Revamped dependency. (Minions-Revamped 0.0.8)
# Updated to 1.16.4
# Modified methods to use MinionTypeConfigurations.
# Modified events to use MinionTypeConfigurations.
# Removed a few listeners.
