name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.0.3
api-version: 1.16
depend: [Minions-Revamped]

# Update 0.0.3 for Minions-Miner

# * Modifed saving minion, to function with new methods introduced in the update for (Minions-Revamped - 0.0.3)