name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.0.4
api-version: 1.16
depend: [Minions-Revamped]

# Update 0.0.4 for Minions-Miner

# * Moved miners task code to MinionPerformTaskEvent. Reduces the risk of the server getting held up on MinionLastPoseEvent.
# * Checks if the item being given to minion matches the item the minion is already holding.
# + If minion is holding an item with efficiency the movement delay will now be affected.