name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.0.7
api-version: 1.13
depend: [Minions-Revamped]

# Update 0.0.7 for Minions-Miner

# Updated Minions-Revamped dependency.
# Set "api-version" to 1.13
# Loads chunk when spawning and unloading minions.
# Cancels chunk unload event for legacy versions. (If Keep_Chunk_Loaded is true)
